version: 0.1

phases:
  pre_build:
    commands:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t gabriprat/hoshinplan:latest .
      - docker tag gabriprat/hoshinplan:latest gabriprat/hoshinplan:latest
  post_build:
    commands:
      - docker push gabriprat/hoshinplan:latest
      - echo Build completed on `date`

